server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/notice
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  servlet:
    multipart:
      max-file-size: 100MB
      location: C:\notice

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

